TARGET = XS1-U16A-128-FB217-C10
#TARGET = XS1-U8A-64-FB96-C5
XCC_FLAGS = -O2 -DUSB_CORE=0 -g
APP_NAME = 
USED_MODULES = module_usb_device module_usb_shared module_xud
VERBOSE = 0

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
